"""init

Revision ID: 0001
Revises: 
Create Date: 2026-09-30 10:39:39.830674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unified_vuln',
    sa.Column('vuln_id', sa.String(length=32), nullable=False),
    sa.Column('schema_version', sa.String(length=8), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('trace_ids', sa.JSON(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('lang', sa.String(length=16), nullable=True),
    sa.Column('cvss', sa.JSON(), nullable=False),
    sa.Column('cwe_ids', sa.JSON(), nullable=False),
    sa.Column('cpe_matches', sa.JSON(), nullable=False),
    sa.Column('ecosystem_packages', sa.JSON(), nullable=False),
    sa.Column('references', sa.JSON(), nullable=False),
    sa.Column('kev', sa.Boolean(), nullable=False),
    sa.Column('epss_score', sa.Float(), nullable=True),
    sa.Column('epss_percentile', sa.Float(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('normalized_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('vuln_id', name=op.f('pk_unified_vuln'))
    )
    op.create_index(op.f('ix_unified_vuln_kev'), 'unified_vuln', ['kev'], unique=False)
    op.create_index(op.f('ix_unified_vuln_normalized_at'), 'unified_vuln', ['normalized_at'], unique=False)
    op.create_index(op.f('ix_unified_vuln_published_at'), 'unified_vuln', ['published_at'], unique=False)
    op.create_table('enriched_vuln',
    sa.Column('vuln_id', sa.String(length=32), nullable=False),
    sa.Column('schema_version', sa.String(length=8), nullable=False),
    sa.Column('affected_assets', sa.JSON(), nullable=False),
    sa.Column('related_papers', sa.JSON(), nullable=False),
    sa.Column('exploits', sa.JSON(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('risk_breakdown', sa.JSON(), nullable=False),
    sa.Column('attack_chain', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('review_status', sa.String(length=16), nullable=False),
    sa.Column('review_notes', sa.JSON(), nullable=False),
    sa.Column('agent_trace', sa.JSON(), nullable=False),
    sa.Column('model_used', sa.String(length=64), nullable=False),
    sa.Column('enriched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['vuln_id'], ['unified_vuln.vuln_id'], name=op.f('fk_enriched_vuln_vuln_id_unified_vuln'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vuln_id', name=op.f('pk_enriched_vuln'))
    )
    op.create_index(op.f('ix_enriched_vuln_enriched_at'), 'enriched_vuln', ['enriched_at'], unique=False)
    op.create_index(op.f('ix_enriched_vuln_review_status'), 'enriched_vuln', ['review_status'], unique=False)
    op.create_index(op.f('ix_enriched_vuln_risk_level'), 'enriched_vuln', ['risk_level'], unique=False)
    op.create_index(op.f('ix_enriched_vuln_risk_score'), 'enriched_vuln', ['risk_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enriched_vuln_risk_score'), table_name='enriched_vuln')
    op.drop_index(op.f('ix_enriched_vuln_risk_level'), table_name='enriched_vuln')
    op.drop_index(op.f('ix_enriched_vuln_review_status'), table_name='enriched_vuln')
    op.drop_index(op.f('ix_enriched_vuln_enriched_at'), table_name='enriched_vuln')
    op.drop_table('enriched_vuln')
    op.drop_index(op.f('ix_unified_vuln_published_at'), table_name='unified_vuln')
    op.drop_index(op.f('ix_unified_vuln_normalized_at'), table_name='unified_vuln')
    op.drop_index(op.f('ix_unified_vuln_kev'), table_name='unified_vuln')
    op.drop_table('unified_vuln')
    # ### end Alembic commands ###
