"""raw_item_and_task_run

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-30 10:55:13.916109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_item',
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('schema_version', sa.String(length=8), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('lang', sa.String(length=16), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('sha256', name=op.f('pk_raw_item'))
    )
    op.create_index(op.f('ix_raw_item_fetched_at'), 'raw_item', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_raw_item_published_at'), 'raw_item', ['published_at'], unique=False)
    op.create_index(op.f('ix_raw_item_source'), 'raw_item', ['source'], unique=False)
    op.create_index('ix_raw_item_source_source_id', 'raw_item', ['source', 'source_id'], unique=False)
    op.create_index(op.f('ix_raw_item_trace_id'), 'raw_item', ['trace_id'], unique=False)
    op.create_table('task_run',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('task_name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched', sa.Integer(), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_run'))
    )
    op.create_index(op.f('ix_task_run_source'), 'task_run', ['source'], unique=False)
    op.create_index(op.f('ix_task_run_started_at'), 'task_run', ['started_at'], unique=False)
    op.create_index(op.f('ix_task_run_status'), 'task_run', ['status'], unique=False)
    op.create_index(op.f('ix_task_run_task_name'), 'task_run', ['task_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_run_task_name'), table_name='task_run')
    op.drop_index(op.f('ix_task_run_status'), table_name='task_run')
    op.drop_index(op.f('ix_task_run_started_at'), table_name='task_run')
    op.drop_index(op.f('ix_task_run_source'), table_name='task_run')
    op.drop_table('task_run')
    op.drop_index(op.f('ix_raw_item_trace_id'), table_name='raw_item')
    op.drop_index('ix_raw_item_source_source_id', table_name='raw_item')
    op.drop_index(op.f('ix_raw_item_source'), table_name='raw_item')
    op.drop_index(op.f('ix_raw_item_published_at'), table_name='raw_item')
    op.drop_index(op.f('ix_raw_item_fetched_at'), table_name='raw_item')
    op.drop_table('raw_item')
    # ### end Alembic commands ###
